/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package market;

import java.text.MessageFormat;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jade
 */
public class supermarket extends javax.swing.JFrame {

    /**
     * Creates new form supermarket
     */
    public supermarket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        nine = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        one = new javax.swing.JButton();
        theree = new javax.swing.JButton();
        two = new javax.swing.JButton();
        siro = new javax.swing.JButton();
        si = new javax.swing.JButton();
        dat = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnPay = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Subtotal = new javax.swing.JTextField();
        Tax = new javax.swing.JTextField();
        Total = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cash = new javax.swing.JLabel();
        Change = new javax.swing.JTextField();
        jtxtDisplay = new javax.swing.JTextField();
        Paymentt = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Chippy = new javax.swing.JPanel();
        PantenBlue = new javax.swing.JButton();
        CreamSilkPink = new javax.swing.JButton();
        PalmoliveRe = new javax.swing.JButton();
        SunsilkPink = new javax.swing.JButton();
        PantenePink = new javax.swing.JButton();
        SunsilkGreen = new javax.swing.JButton();
        CreamSilkGold = new javax.swing.JButton();
        Keratin = new javax.swing.JButton();
        SafeguardWhite = new javax.swing.JButton();
        IrishSpring = new javax.swing.JButton();
        SafeguardYelow = new javax.swing.JButton();
        Ligo = new javax.swing.JButton();
        CenturyTuna = new javax.swing.JButton();
        Argentina = new javax.swing.JButton();
        Maling = new javax.swing.JButton();
        PancitCanyton = new javax.swing.JButton();
        Nudels = new javax.swing.JButton();
        PotatoCrisp = new javax.swing.JButton();
        PalmolivePink = new javax.swing.JButton();
        Vcut = new javax.swing.JButton();
        Fishda = new javax.swing.JButton();
        Piattos = new javax.swing.JButton();
        Chipeh = new javax.swing.JButton();
        Mobt = new javax.swing.JButton();
        Mango = new javax.swing.JButton();
        Strabwryy = new javax.swing.JButton();
        Grapes = new javax.swing.JButton();
        Apple = new javax.swing.JButton();
        Banna = new javax.swing.JButton();
        Orange = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        barcode = new javax.swing.JTextField();

        jTextField13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13.setText("₱70.00");
        jTextField13.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTextField14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.setText("₱70.00");
        jTextField14.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTextField15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField15.setText("₱70.00");
        jTextField15.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTextField16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField16.setText("₱70.00");
        jTextField16.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTextField17.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jTextField17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField17.setText("₱70.00");
        jTextField17.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTextField18.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jTextField18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField18.setText("₱70.00");
        jTextField18.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        nine.setBackground(new java.awt.Color(255, 204, 102));
        nine.setFont(new java.awt.Font("OCR A Extended", 3, 36)); // NOI18N
        nine.setText("9");
        nine.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });

        seven.setBackground(new java.awt.Color(255, 204, 102));
        seven.setFont(new java.awt.Font("OCR A Extended", 3, 36)); // NOI18N
        seven.setText("7");
        seven.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });

        eight.setBackground(new java.awt.Color(255, 204, 102));
        eight.setFont(new java.awt.Font("OCR A Extended", 3, 36)); // NOI18N
        eight.setText("8");
        eight.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });

        four.setBackground(new java.awt.Color(255, 204, 102));
        four.setFont(new java.awt.Font("OCR A Extended", 3, 36)); // NOI18N
        four.setText("4");
        four.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });

        five.setBackground(new java.awt.Color(255, 204, 102));
        five.setFont(new java.awt.Font("OCR A Extended", 3, 36)); // NOI18N
        five.setText("5");
        five.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });

        six.setBackground(new java.awt.Color(255, 204, 102));
        six.setFont(new java.awt.Font("OCR A Extended", 3, 36)); // NOI18N
        six.setText("6");
        six.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });

        one.setBackground(new java.awt.Color(255, 204, 102));
        one.setFont(new java.awt.Font("OCR A Extended", 3, 36)); // NOI18N
        one.setText("1");
        one.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });

        theree.setBackground(new java.awt.Color(255, 204, 102));
        theree.setFont(new java.awt.Font("OCR A Extended", 3, 36)); // NOI18N
        theree.setText("3");
        theree.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        theree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thereeActionPerformed(evt);
            }
        });

        two.setBackground(new java.awt.Color(255, 204, 102));
        two.setFont(new java.awt.Font("OCR A Extended", 3, 36)); // NOI18N
        two.setText("2");
        two.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });

        siro.setBackground(new java.awt.Color(255, 204, 102));
        siro.setFont(new java.awt.Font("OCR A Extended", 3, 36)); // NOI18N
        siro.setText("0");
        siro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        siro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siroActionPerformed(evt);
            }
        });

        si.setBackground(new java.awt.Color(255, 204, 102));
        si.setFont(new java.awt.Font("OCR A Extended", 3, 36)); // NOI18N
        si.setText("c");
        si.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siActionPerformed(evt);
            }
        });

        dat.setBackground(new java.awt.Color(255, 204, 102));
        dat.setFont(new java.awt.Font("OCR A Extended", 3, 36)); // NOI18N
        dat.setText(".");
        dat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(siro, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dat, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(si, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(theree, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(theree, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(siro, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dat, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(si, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 80, 270, 370));

        jPanel3.setBackground(new java.awt.Color(255, 204, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jPanel5.setBackground(new java.awt.Color(255, 204, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnPay.setBackground(new java.awt.Color(255, 255, 153));
        btnPay.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        btnPay.setForeground(new java.awt.Color(255, 102, 0));
        btnPay.setText("Pay");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        btnPrint.setBackground(new java.awt.Color(255, 255, 153));
        btnPrint.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 102, 0));
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        btnRemove.setBackground(new java.awt.Color(255, 255, 153));
        btnRemove.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(255, 102, 0));
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(255, 255, 153));
        btnReset.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 102, 0));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(btnPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPrint, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 204, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("SubTotal: ");

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Total:");

        jLabel3.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 51));
        jLabel3.setText("Tax:");

        Subtotal.setBackground(new java.awt.Color(255, 255, 153));
        Subtotal.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N

        Tax.setBackground(new java.awt.Color(255, 255, 153));
        Tax.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        Tax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaxActionPerformed(evt);
            }
        });

        Total.setBackground(new java.awt.Color(255, 255, 153));
        Total.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Tax, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(74, 74, 74)
                        .addComponent(Subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(Subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(Tax, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 204, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel4.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 51));
        jLabel4.setText("Payment:");

        jLabel5.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("Change:");

        cash.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        cash.setForeground(new java.awt.Color(255, 102, 0));
        cash.setText("Cash:");

        Change.setBackground(new java.awt.Color(255, 255, 153));
        Change.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N

        jtxtDisplay.setBackground(new java.awt.Color(255, 255, 153));
        jtxtDisplay.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N

        Paymentt.setBackground(new java.awt.Color(255, 255, 153));
        Paymentt.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        Paymentt.setForeground(new java.awt.Color(153, 0, 0));
        Paymentt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "GCash", "Credit Card", "Debit Card" }));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cash)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Paymentt, javax.swing.GroupLayout.Alignment.LEADING, 0, 172, Short.MAX_VALUE)
                    .addComponent(jtxtDisplay, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Change))
                .addGap(267, 267, 267))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Paymentt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jtxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Change, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(cash)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(294, 294, 294))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(35, 35, 35))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 1320, 160));

        jTable1.setBackground(new java.awt.Color(255, 204, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Qty", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 340, 300));

        Chippy.setBackground(new java.awt.Color(255, 204, 153));
        Chippy.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Chippy.setForeground(new java.awt.Color(0, 102, 102));
        Chippy.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PantenBlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pntn.jpg"))); // NOI18N
        PantenBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PantenBlueActionPerformed(evt);
            }
        });
        Chippy.add(PantenBlue, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 19, 87, 80));

        CreamSilkPink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CRMSLK.jpg"))); // NOI18N
        CreamSilkPink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreamSilkPinkActionPerformed(evt);
            }
        });
        Chippy.add(CreamSilkPink, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 87, 80));

        PalmoliveRe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/palmolive.jpg"))); // NOI18N
        PalmoliveRe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PalmoliveReActionPerformed(evt);
            }
        });
        Chippy.add(PalmoliveRe, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 19, 87, 80));

        SunsilkPink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/snslk2.jpg"))); // NOI18N
        SunsilkPink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SunsilkPinkActionPerformed(evt);
            }
        });
        Chippy.add(SunsilkPink, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 19, 87, 80));

        PantenePink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pntn2.jpg"))); // NOI18N
        PantenePink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PantenePinkActionPerformed(evt);
            }
        });
        Chippy.add(PantenePink, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 19, 87, 80));

        SunsilkGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/snslk.jpg"))); // NOI18N
        SunsilkGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SunsilkGreenActionPerformed(evt);
            }
        });
        Chippy.add(SunsilkGreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 19, 87, 80));

        CreamSilkGold.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/crmslk2.jpg"))); // NOI18N
        CreamSilkGold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreamSilkGoldActionPerformed(evt);
            }
        });
        Chippy.add(CreamSilkGold, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 87, 80));

        Keratin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/crmslk3.jpg"))); // NOI18N
        Keratin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeratinActionPerformed(evt);
            }
        });
        Chippy.add(Keratin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 87, 80));

        SafeguardWhite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Safeguard-Soap-Pure-white-85g.jpg"))); // NOI18N
        SafeguardWhite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SafeguardWhiteActionPerformed(evt);
            }
        });
        Chippy.add(SafeguardWhite, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 87, 80));

        IrishSpring.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/667d16a86eaf973adb45982b9b447fc8.png"))); // NOI18N
        IrishSpring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrishSpringActionPerformed(evt);
            }
        });
        Chippy.add(IrishSpring, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 87, 80));

        SafeguardYelow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/10-32.jpg"))); // NOI18N
        SafeguardYelow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SafeguardYelowActionPerformed(evt);
            }
        });
        Chippy.add(SafeguardYelow, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 87, 80));

        Ligo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Ligo-Sardines-Red-48-425G.jpg"))); // NOI18N
        Ligo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LigoActionPerformed(evt);
            }
        });
        Chippy.add(Ligo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 87, 80));

        CenturyTuna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cntry.jpg"))); // NOI18N
        CenturyTuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CenturyTunaActionPerformed(evt);
            }
        });
        Chippy.add(CenturyTuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 87, 80));

        Argentina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/argentine-corned-beef-can-150g.jpg"))); // NOI18N
        Argentina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArgentinaActionPerformed(evt);
            }
        });
        Chippy.add(Argentina, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 87, 80));

        Maling.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/maling.jpg"))); // NOI18N
        Maling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MalingActionPerformed(evt);
            }
        });
        Chippy.add(Maling, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 87, 80));

        PancitCanyton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pnctccnton.jpg"))); // NOI18N
        PancitCanyton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PancitCanytonActionPerformed(evt);
            }
        });
        Chippy.add(PancitCanyton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 87, 80));

        Nudels.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nudesl.jpg"))); // NOI18N
        Nudels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NudelsActionPerformed(evt);
            }
        });
        Chippy.add(Nudels, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 87, 80));

        PotatoCrisp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pttsricp.png"))); // NOI18N
        PotatoCrisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PotatoCrispActionPerformed(evt);
            }
        });
        Chippy.add(PotatoCrisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 87, 80));

        PalmolivePink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/palmolive 2.jpg"))); // NOI18N
        PalmolivePink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PalmolivePinkActionPerformed(evt);
            }
        });
        Chippy.add(PalmolivePink, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 19, 87, 80));

        Vcut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/vcut.jpg"))); // NOI18N
        Vcut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VcutActionPerformed(evt);
            }
        });
        Chippy.add(Vcut, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 87, 80));

        Fishda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fshda.png"))); // NOI18N
        Fishda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FishdaActionPerformed(evt);
            }
        });
        Chippy.add(Fishda, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 87, 80));

        Piattos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pts.jpg"))); // NOI18N
        Piattos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PiattosActionPerformed(evt);
            }
        });
        Chippy.add(Piattos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 87, 80));

        Chipeh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/chpy.png"))); // NOI18N
        Chipeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChipehActionPerformed(evt);
            }
        });
        Chippy.add(Chipeh, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 87, 80));

        Mobt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mb.jpg"))); // NOI18N
        Mobt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MobtActionPerformed(evt);
            }
        });
        Chippy.add(Mobt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, 87, 80));

        Mango.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mngo.jpg"))); // NOI18N
        Mango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MangoActionPerformed(evt);
            }
        });
        Chippy.add(Mango, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 87, 80));

        Strabwryy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/strw.jpg"))); // NOI18N
        Strabwryy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StrabwryyActionPerformed(evt);
            }
        });
        Chippy.add(Strabwryy, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 87, 80));

        Grapes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/grp.jpg"))); // NOI18N
        Grapes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrapesActionPerformed(evt);
            }
        });
        Chippy.add(Grapes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 570, 87, 80));

        Apple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/apple.jpg"))); // NOI18N
        Apple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppleActionPerformed(evt);
            }
        });
        Chippy.add(Apple, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 570, 87, 80));

        Banna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bnna.jpg"))); // NOI18N
        Banna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BannaActionPerformed(evt);
            }
        });
        Chippy.add(Banna, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 570, 87, 80));

        Orange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ronge.jpg"))); // NOI18N
        Orange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrangeActionPerformed(evt);
            }
        });
        Chippy.add(Orange, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 570, 87, 80));

        jLabel6.setText("jLabel6");
        Chippy.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        Chippy.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 580, 10));
        Chippy.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 590, -1));
        Chippy.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 423, 590, 0));
        Chippy.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 590, 0));
        Chippy.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 580, 0));

        jTextField1.setBackground(new java.awt.Color(255, 204, 102));
        jTextField1.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("₱65.00");
        jTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Chippy.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 80, -1));

        jTextField2.setBackground(new java.awt.Color(255, 204, 102));
        jTextField2.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("₱70.00");
        jTextField2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Chippy.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 80, -1));

        jTextField3.setBackground(new java.awt.Color(255, 204, 102));
        jTextField3.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("₱70.00");
        jTextField3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Chippy.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 80, -1));

        jTextField4.setBackground(new java.awt.Color(255, 204, 102));
        jTextField4.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("₱165.00");
        jTextField4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        Chippy.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 80, -1));

        jTextField5.setBackground(new java.awt.Color(255, 204, 102));
        jTextField5.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("₱165.00");
        jTextField5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Chippy.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 80, -1));

        jTextField6.setBackground(new java.awt.Color(255, 204, 102));
        jTextField6.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("₱65.00");
        jTextField6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Chippy.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 80, -1));

        jTextField7.setBackground(new java.awt.Color(255, 204, 102));
        jTextField7.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("₱80.00");
        jTextField7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Chippy.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 80, -1));

        jTextField8.setBackground(new java.awt.Color(255, 204, 102));
        jTextField8.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("₱80.00");
        jTextField8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Chippy.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 80, -1));

        jTextField9.setBackground(new java.awt.Color(255, 204, 102));
        jTextField9.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setText("₱120.25");
        jTextField9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Chippy.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 80, -1));

        jTextField10.setBackground(new java.awt.Color(255, 204, 102));
        jTextField10.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("₱65.00");
        jTextField10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Chippy.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 80, -1));

        jTextField11.setBackground(new java.awt.Color(255, 204, 102));
        jTextField11.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setText("₱89.20");
        jTextField11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Chippy.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 80, -1));

        jTextField12.setBackground(new java.awt.Color(255, 204, 102));
        jTextField12.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setText("₱75.90");
        jTextField12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Chippy.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 80, -1));

        jTextField19.setBackground(new java.awt.Color(255, 204, 102));
        jTextField19.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jTextField19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField19.setText("₱27.00");
        jTextField19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Chippy.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 80, -1));

        jTextField20.setBackground(new java.awt.Color(255, 204, 102));
        jTextField20.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jTextField20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField20.setText("₱45.00");
        jTextField20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Chippy.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 80, -1));

        jTextField21.setBackground(new java.awt.Color(255, 204, 102));
        jTextField21.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jTextField21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField21.setText("₱28.60");
        jTextField21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Chippy.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 80, -1));

        jTextField22.setBackground(new java.awt.Color(255, 204, 102));
        jTextField22.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jTextField22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField22.setText("₱80.00");
        jTextField22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Chippy.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 80, -1));

        jTextField23.setBackground(new java.awt.Color(255, 204, 102));
        jTextField23.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jTextField23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField23.setText("₱70.00");
        jTextField23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Chippy.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 80, -1));

        jTextField24.setBackground(new java.awt.Color(255, 204, 102));
        jTextField24.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jTextField24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField24.setText("₱11.00");
        jTextField24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Chippy.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 80, -1));

        jTextField25.setBackground(new java.awt.Color(255, 204, 102));
        jTextField25.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jTextField25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField25.setText("₱7.50");
        jTextField25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Chippy.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 80, -1));

        jTextField26.setBackground(new java.awt.Color(255, 204, 102));
        jTextField26.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jTextField26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField26.setText("₱14.50");
        jTextField26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Chippy.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 80, -1));

        jTextField27.setBackground(new java.awt.Color(255, 204, 102));
        jTextField27.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jTextField27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField27.setText("₱24.00");
        jTextField27.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Chippy.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 530, 80, -1));

        jTextField31.setBackground(new java.awt.Color(255, 204, 102));
        jTextField31.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jTextField31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField31.setText("₱30.00");
        jTextField31.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Chippy.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 80, -1));

        jTextField32.setBackground(new java.awt.Color(255, 204, 102));
        jTextField32.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jTextField32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField32.setText("₱120.00");
        jTextField32.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Chippy.add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 660, 80, -1));

        jTextField33.setBackground(new java.awt.Color(255, 204, 102));
        jTextField33.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jTextField33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField33.setText("₱63.00");
        jTextField33.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Chippy.add(jTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 660, 80, -1));

        jTextField34.setBackground(new java.awt.Color(255, 204, 102));
        jTextField34.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jTextField34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField34.setText("₱20.00");
        jTextField34.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Chippy.add(jTextField34, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 660, 80, -1));

        jTextField35.setBackground(new java.awt.Color(255, 204, 102));
        jTextField35.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jTextField35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField35.setText("₱65.00");
        jTextField35.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField35ActionPerformed(evt);
            }
        });
        Chippy.add(jTextField35, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 660, 80, -1));

        jTextField36.setBackground(new java.awt.Color(255, 204, 102));
        jTextField36.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jTextField36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField36.setText("₱30.00");
        jTextField36.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Chippy.add(jTextField36, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 660, 80, -1));

        jTextField37.setBackground(new java.awt.Color(255, 204, 102));
        jTextField37.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jTextField37.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField37.setText("₱7.50");
        jTextField37.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Chippy.add(jTextField37, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 80, -1));

        jTextField38.setBackground(new java.awt.Color(255, 204, 102));
        jTextField38.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jTextField38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField38.setText("₱7.50");
        jTextField38.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Chippy.add(jTextField38, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, 80, -1));

        jTextField39.setBackground(new java.awt.Color(255, 204, 102));
        jTextField39.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jTextField39.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField39.setText("₱9.00");
        jTextField39.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Chippy.add(jTextField39, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, 80, -1));

        jScrollPane2.setViewportView(Chippy);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 600, 360));

        jPanel1.setBackground(new java.awt.Color(161, 124, 87));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0)));

        jLabel7.setFont(new java.awt.Font("Kristen ITC", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("PISHA MART");

        barcode.setFont(new java.awt.Font("3 of 9 Barcode", 0, 36)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(352, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(286, 286, 286))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(299, 299, 299))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                .addComponent(barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1270, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   // ============================FUNCTIONS============================
    public void ItemCost(){
 
        double sum = 0;
        
        for (int i = 0; i < jTable1.getRowCount(); i++)
        {
            sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        }
        Subtotal.setText(Double.toString(sum));
        double tutal = Double.parseDouble( Subtotal.getText());
        
        double tx = (tutal * 0.2 )/100;
        String iTaxTotal = String.format("₱ %.2f", tx);
        Tax.setText(iTaxTotal);
        
        String SubTotal = String.format("₱ %.2f", tutal);
        Subtotal.setText(SubTotal);
        
        String total = String.format("₱ %.2f", tutal + tx);
        Total.setText(total);
        
        String brcd = String.format(Total.getText());
        barcode.setText(brcd);
        
        
    }
     // ============================Change part============================
    public void Changee()
    {
        double sum  =0;
        double tax = 0.2;
        double cash = Double.parseDouble( jtxtDisplay.getText());
        
        for (int i = 0; i < jTable1.getRowCount(); i++)
        {
            sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        }
        
        double tx = (sum * 0.2 )/100;
        double cChange = (cash - (sum + tx));
        
        String ChangeG = String.format("₱ %.2f", cChange);
        Change.setText(ChangeG);
    }
    
    
    
    
    
    
    
    
    private void TaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TaxActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        if(Paymentt.getSelectedItem().equals("Cash"))
        {
        Changee();
    }
        else{
                Change.setText("");
                jtxtDisplay.setText("");
                }
 
    }//GEN-LAST:event_btnPayActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        
        String Putnumber = jtxtDisplay. getText();
        
        if (Putnumber == ""){
            jtxtDisplay.setText(seven.getText());
        }
        
        else{
            Putnumber = jtxtDisplay. getText() + seven.getText();
            jtxtDisplay.setText(Putnumber);
        }
    }//GEN-LAST:event_sevenActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        String Putnumber = jtxtDisplay. getText();
        
        if (Putnumber == ""){
            jtxtDisplay.setText(eight.getText());
        }
        
        else{
            Putnumber = jtxtDisplay. getText() + eight.getText();
            jtxtDisplay.setText(Putnumber);
        }
    }//GEN-LAST:event_eightActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
       String Putnumber = jtxtDisplay. getText();
        
        if (Putnumber == ""){
            jtxtDisplay.setText(nine.getText());
        }
        
        else{
            Putnumber = jtxtDisplay. getText() + nine.getText();
            jtxtDisplay.setText(Putnumber);
        }
    }//GEN-LAST:event_nineActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        String Putnumber = jtxtDisplay. getText();
        
        if (Putnumber == ""){
            jtxtDisplay.setText(four.getText());
        }
        
        else{
            Putnumber = jtxtDisplay. getText() + four.getText();
            jtxtDisplay.setText(Putnumber);
        }
    }//GEN-LAST:event_fourActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
String Putnumber = jtxtDisplay. getText();
        
        if (Putnumber == ""){
            jtxtDisplay.setText(five.getText());
        }
        
        else{
            Putnumber = jtxtDisplay. getText() + five.getText();
            jtxtDisplay.setText(Putnumber);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_fiveActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        String Putnumber = jtxtDisplay. getText();

        if (Putnumber == ""){
            jtxtDisplay.setText(six.getText());
        }

        else{
            Putnumber = jtxtDisplay. getText() + six.getText();
            jtxtDisplay.setText(Putnumber);
        }
    }//GEN-LAST:event_sixActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        String Putnumber = jtxtDisplay. getText();

        if (Putnumber == ""){
            jtxtDisplay.setText(one.getText());
        }

        else{
            Putnumber = jtxtDisplay. getText() + one.getText();
            jtxtDisplay.setText(Putnumber);
        }
    }//GEN-LAST:event_oneActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        String Putnumber = jtxtDisplay. getText();

        if (Putnumber == ""){
            jtxtDisplay.setText(two.getText());
        }

        else{
            Putnumber = jtxtDisplay. getText() + two.getText();
            jtxtDisplay.setText(Putnumber);
        }
    }//GEN-LAST:event_twoActionPerformed

    private void thereeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thereeActionPerformed
        String Putnumber = jtxtDisplay. getText();

        if (Putnumber == ""){
            jtxtDisplay.setText(theree.getText());
        }

        else{
            Putnumber = jtxtDisplay. getText() + theree.getText();
            jtxtDisplay.setText(Putnumber);
        }
    }//GEN-LAST:event_thereeActionPerformed

    private void siroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siroActionPerformed
        String Putnumber = jtxtDisplay. getText();

        if (Putnumber == ""){
            jtxtDisplay.setText(siro.getText());
        }

        else{
            Putnumber = jtxtDisplay. getText() + siro.getText();
            jtxtDisplay.setText(Putnumber);
        }
    }//GEN-LAST:event_siroActionPerformed

    private void datActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datActionPerformed

        if(!jtxtDisplay.getText().contains(".")){
            jtxtDisplay.setText(jtxtDisplay.getText() + dat.getText());
        }
    }//GEN-LAST:event_datActionPerformed

    private void siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siActionPerformed
        jtxtDisplay.setText("");
        Change.setText("");
    }//GEN-LAST:event_siActionPerformed

    private void PantenBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PantenBlueActionPerformed
       double PriceOfItem = 165.00;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Pantene Blue", "1", PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_PantenBlueActionPerformed

    private void CreamSilkPinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreamSilkPinkActionPerformed
        double PriceOfItem = 80.00;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"CreamSilk Pink", "1", PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_CreamSilkPinkActionPerformed

    private void PalmoliveReActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PalmoliveReActionPerformed
        double PriceOfItem = 70.00;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Palmolive Red", "1", PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_PalmoliveReActionPerformed

    private void SunsilkPinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SunsilkPinkActionPerformed
        double PriceOfItem = 65.00;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Sunsilk Pink", "1", PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_SunsilkPinkActionPerformed

    private void PantenePinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PantenePinkActionPerformed
        double PriceOfItem = 165.00;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Pantene Pink", "1", PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_PantenePinkActionPerformed

    private void SunsilkGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SunsilkGreenActionPerformed
        double PriceOfItem = 65.00;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Sunsilk Green", "1", PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_SunsilkGreenActionPerformed

    private void PalmolivePinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PalmolivePinkActionPerformed
        double PriceOfItem = 70.00;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Palmolive Pink", "1", PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_PalmolivePinkActionPerformed

    private void CreamSilkGoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreamSilkGoldActionPerformed
        double PriceOfItem = 80.00;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"CreamSilk Gold", "1", PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_CreamSilkGoldActionPerformed

    private void KeratinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeratinActionPerformed
        double PriceOfItem = 120.00;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"CreamSilk Keratin", "1", PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_KeratinActionPerformed

    private void SafeguardWhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SafeguardWhiteActionPerformed
        double PriceOfItem = 65.00;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Safeguard White", "1", PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_SafeguardWhiteActionPerformed

    private void IrishSpringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrishSpringActionPerformed
        double PriceOfItem = 89.20;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Irish Spring", "1", PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_IrishSpringActionPerformed

    private void SafeguardYelowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SafeguardYelowActionPerformed
        double PriceOfItem = 75.90;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Safeguard Yellow", "1", PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_SafeguardYelowActionPerformed

    private void LigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LigoActionPerformed
       double PriceOfItem = 27.00;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Ligo Red Spicy", "1", PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_LigoActionPerformed

    private void CenturyTunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CenturyTunaActionPerformed
        double PriceOfItem = 45.00;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Century Tuna", "1", PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_CenturyTunaActionPerformed

    private void ArgentinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArgentinaActionPerformed
       double PriceOfItem = 28.60;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Argetina Corned Beef", "1", PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_ArgentinaActionPerformed

    private void MalingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MalingActionPerformed
        double PriceOfItem = 80.00;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Maling", "1", PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_MalingActionPerformed

    private void PancitCanytonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PancitCanytonActionPerformed
        double PriceOfItem = 14.50;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Pancit Canton", "1", PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_PancitCanytonActionPerformed

    private void NudelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NudelsActionPerformed
       double PriceOfItem = 11.00;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"LuckyMe Beef", "1", PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_NudelsActionPerformed

    private void PotatoCrispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PotatoCrispActionPerformed
       double PriceOfItem = 14.50;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Potato Crisps", "1", PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_PotatoCrispActionPerformed

    private void VcutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VcutActionPerformed
        double PriceOfItem = 14.50;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Vcut", "1", PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_VcutActionPerformed

    private void FishdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FishdaActionPerformed
        double PriceOfItem = 7.50;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Fishda", "1", PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_FishdaActionPerformed

    private void PiattosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PiattosActionPerformed
        double PriceOfItem = 28.50;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Piattos", "1", PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_PiattosActionPerformed

    private void ChipehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChipehActionPerformed
       double PriceOfItem = 9.00;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Chippy", "1", PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_ChipehActionPerformed

    private void MobtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MobtActionPerformed
       double PriceOfItem = 24.00;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Moby Caramel", "1", PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_MobtActionPerformed

    private void MangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MangoActionPerformed
        double PriceOfItem = 30.00;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Mango", "1", PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_MangoActionPerformed

    private void StrabwryyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StrabwryyActionPerformed
        double PriceOfItem = 120.00;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Strawberry", "1", PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_StrabwryyActionPerformed

    private void GrapesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrapesActionPerformed
       double PriceOfItem = 63.00;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Grapes", "1", PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_GrapesActionPerformed

    private void AppleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppleActionPerformed
        double PriceOfItem = 20.00;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Apple", "1", PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_AppleActionPerformed

    private void BannaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BannaActionPerformed
        double PriceOfItem = 65.00;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Banana", "1", PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_BannaActionPerformed

    private void OrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrangeActionPerformed
        double PriceOfItem = 30.00;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Orange", "1", PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_OrangeActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code her
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField35ActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.setRowCount(0);
        Change.setText("");
        Tax.setText("");
        Total.setText("");
        Subtotal.setText("");
        jtxtDisplay.setText("");
        barcode.setText("");
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
      MessageFormat header = new MessageFormat("PISHA MART");
      MessageFormat footer = new MessageFormat("Page {0, number, integer}");
      
      try{
          jTable1.print(JTable.PrintMode.NORMAL, header,footer);
      }
      catch(java.awt.print.PrinterException e){
          System.err.format("No Printer Found! ",e.getMessage());
      }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       
        int RemoveItem = jTable1.getSelectedRow();
        
        if(RemoveItem >= 0){
        model.removeRow(RemoveItem);
    }
        ItemCost();
        
        if(Paymentt.getSelectedItem().equals("Cash"))
        {
        Changee();
    }
        else{
                Change.setText("");
                jtxtDisplay.setText("");
                }
        
        
        
    }//GEN-LAST:event_btnRemoveActionPerformed
private JFrame frame;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supermarket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supermarket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supermarket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supermarket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new supermarket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Apple;
    private javax.swing.JButton Argentina;
    private javax.swing.JButton Banna;
    private javax.swing.JButton CenturyTuna;
    private javax.swing.JTextField Change;
    private javax.swing.JButton Chipeh;
    private javax.swing.JPanel Chippy;
    private javax.swing.JButton CreamSilkGold;
    private javax.swing.JButton CreamSilkPink;
    private javax.swing.JButton Fishda;
    private javax.swing.JButton Grapes;
    private javax.swing.JButton IrishSpring;
    private javax.swing.JButton Keratin;
    private javax.swing.JButton Ligo;
    private javax.swing.JButton Maling;
    private javax.swing.JButton Mango;
    private javax.swing.JButton Mobt;
    private javax.swing.JButton Nudels;
    private javax.swing.JButton Orange;
    private javax.swing.JButton PalmolivePink;
    private javax.swing.JButton PalmoliveRe;
    private javax.swing.JButton PancitCanyton;
    private javax.swing.JButton PantenBlue;
    private javax.swing.JButton PantenePink;
    private javax.swing.JComboBox<String> Paymentt;
    private javax.swing.JButton Piattos;
    private javax.swing.JButton PotatoCrisp;
    private javax.swing.JButton SafeguardWhite;
    private javax.swing.JButton SafeguardYelow;
    private javax.swing.JButton Strabwryy;
    private javax.swing.JTextField Subtotal;
    private javax.swing.JButton SunsilkGreen;
    private javax.swing.JButton SunsilkPink;
    private javax.swing.JTextField Tax;
    private javax.swing.JTextField Total;
    private javax.swing.JButton Vcut;
    private javax.swing.JTextField barcode;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel cash;
    private javax.swing.JButton dat;
    private javax.swing.JButton eight;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JButton seven;
    private javax.swing.JButton si;
    private javax.swing.JButton siro;
    private javax.swing.JButton six;
    private javax.swing.JButton theree;
    private javax.swing.JButton two;
    // End of variables declaration//GEN-END:variables
}
